In [154]:
import pandas as pd

In [155]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

In [156]:
#load_path = 'D:\EECE499\Features\\'
load_path = '..\..\\'

In [157]:
Features = pd.read_excel(load_path + 'Features.xlsx')

In [158]:
Features

avg_minima_con  avg_minima_res  mean_abs_first_derivative_con  \
324         0.012727        0.012727                   9.971316e-13   
325         0.004064        0.004064                   1.990523e-10   
326         0.029583        0.029583                   9.258622e-13   
327         0.025690        0.025690                   1.494468e-12   
328         0.010728        0.010728                   4.046315e-10   
329         0.002781        0.002642                   5.011512e-10   
330         0.008005        0.008005                   2.013854e-12   
331         0.016494        0.016494                   3.906971e-10   
332         0.043606        0.043493                   6.097902e-11   
333         0.025645        0.025645                   1.424005e-12   
334         0.009612        0.009612                   2.434530e-12   
335         0.020526        0.020445                   3.734069e-12   
336         0.015145        0.015145                   1.963758e-12   
337         0.010842        0.010703                   1.956187e-12   
338         0.006231        0.006231                   8.073306e-10   
339         0.002189        0.002067                   2.219786e-10   
340         0.003562        0.003562                   1.712330e-10   
341         0.017807        0.017711                   2.373803e-12   
342         0.020849        0.020849                   2.472942e-12   
343         0.007661        0.007661                   4.295487e-10   
344         0.039292        0.039377                   1.437205e-12   
345         0.003219        0.003219                   2.048993e-12   
346         0.001407        0.001407                   1.961632e-10   
347         0.011442        0.011442                   3.881574e-12   
348         0.007354        0.007354                   2.312072e-12   
349         0.004722        0.004814                   1.696337e-10   
350         0.027541        0.027437                   1.074685e-12   
351         0.010557        0.010472                   2.983095e-10   
352         0.007449        0.007449                   4.594592e-10   
353         0.024793        0.024701                   4.518233e-12   
...              ...             ...                            ...   
1270        0.008152        0.008152                   5.964774e-11   
1271        0.010520        0.010520                   4.829972e-11   
1272        0.008588        0.008588                   1.482818e-09   
1273        0.003199        0.003338                   7.110629e-11   
1274        0.005243        0.005385                   6.189504e-11   
1275        0.006420        0.006541                   6.482895e-11   
1276        0.017719        0.017719                   3.150532e-11   
1277        0.002985        0.002985                   3.645461e-11   
1278        0.003642        0.003642                   5.258986e-11   
1279        0.010998        0.011119                   6.474056e-10   
1280        0.004650        0.004650                   3.388486e-11   
1281        0.007568        0.007568                   3.018766e-11   
1282        0.002923        0.002923                   1.108147e-10   
1283        0.005596        0.005679                   6.910604e-11   
1284        0.006880        0.006944                   5.598735e-11   
1285        0.004168        0.004075                   2.969324e-09   
1286        0.016341        0.016341                   3.391028e-11   
1287        0.008561        0.008476                   2.420838e-09   
1288        0.009888        0.009888                   3.752861e-11   
1289        0.007674        0.007674                   3.491194e-11   
1290        0.014028        0.014086                   3.166324e-11   
1291        0.007321        0.007321                   4.102537e-11   
1292        0.004951        0.004951                   9.056326e-11   
1293        0.004384        0.004384                   6.783239e-11   
1294        0.011560        0.

In [159]:
Features.iloc[:, -5].head()

324    4
325    4
326    3
327    4
328    4
Name: arousal, dtype: int64

# Arousal

In [223]:
X = Features.iloc[:, :-5].values
y = Features.iloc[:, -5].values

In [224]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [225]:
standard_scaler = StandardScaler()
X_train = standard_scaler.fit_transform(X_train)
X_test = standard_scaler.transform(X_test)

In [226]:
classifier = LogisticRegression(random_state = 0, solver='lbfgs', max_iter=10000)
classifier.fit(X_train, y_train)

C:\Users\Danny\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=10000, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [227]:
y_pred = classifier.predict(X_test)

In [228]:
confusion_mtrx = confusion_matrix(y_test, y_pred)

In [229]:
confusion_mtrx

array([[ 0,  0,  0,  2,  1,  0],
       [ 0,  0,  0,  2,  1,  0],
       [ 0,  0,  0,  5,  6,  1],
       [ 1,  0,  0, 27, 35,  6],
       [ 0,  2,  1, 13, 59, 11],
       [ 0,  0,  0, 12, 20,  8]], dtype=int64)

In [230]:
accuracy = accuracy_score(y_test, y_pred)

In [231]:
accuracy

0.4413145539906103

# Engaging

In [223]:
X = Features.iloc[:, :-5].values
y = Features.iloc[:, -4].values

In [224]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [225]:
standard_scaler = StandardScaler()
X_train = standard_scaler.fit_transform(X_train)
X_test = standard_scaler.transform(X_test)

In [226]:
classifier = LogisticRegression(random_state = 0, solver='lbfgs', max_iter=10000)
classifier.fit(X_train, y_train)

C:\Users\Danny\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=10000, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [227]:
y_pred = classifier.predict(X_test)

In [228]:
confusion_mtrx = confusion_matrix(y_test, y_pred)

In [229]:
confusion_mtrx

array([[ 0,  0,  0,  2,  1,  0],
       [ 0,  0,  0,  2,  1,  0],
       [ 0,  0,  0,  5,  6,  1],
       [ 1,  0,  0, 27, 35,  6],
       [ 0,  2,  1, 13, 59, 11],
       [ 0,  0,  0, 12, 20,  8]], dtype=int64)

In [230]:
accuracy = accuracy_score(y_test, y_pred)

In [231]:
accuracy

0.4413145539906103

# Familiarity

In [223]:
X = Features.iloc[:, :-5].values
y = Features.iloc[:, -3].values

In [224]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [225]:
standard_scaler = StandardScaler()
X_train = standard_scaler.fit_transform(X_train)
X_test = standard_scaler.transform(X_test)

In [226]:
classifier = LogisticRegression(random_state = 0, solver='lbfgs', max_iter=10000)
classifier.fit(X_train, y_train)

C:\Users\Danny\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=10000, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [227]:
y_pred = classifier.predict(X_test)

In [228]:
confusion_mtrx = confusion_matrix(y_test, y_pred)

In [229]:
confusion_mtrx

array([[ 0,  0,  0,  2,  1,  0],
       [ 0,  0,  0,  2,  1,  0],
       [ 0,  0,  0,  5,  6,  1],
       [ 1,  0,  0, 27, 35,  6],
       [ 0,  2,  1, 13, 59, 11],
       [ 0,  0,  0, 12, 20,  8]], dtype=int64)

In [230]:
accuracy = accuracy_score(y_test, y_pred)

In [231]:
accuracy

0.4413145539906103

# Liking

In [223]:
X = Features.iloc[:, :-5].values
y = Features.iloc[:, -5].values

In [224]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [225]:
standard_scaler = StandardScaler()
X_train = standard_scaler.fit_transform(X_train)
X_test = standard_scaler.transform(X_test)

In [226]:
classifier = LogisticRegression(random_state = 0, solver='lbfgs', max_iter=10000)
classifier.fit(X_train, y_train)

C:\Users\Danny\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=10000, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [227]:
y_pred = classifier.predict(X_test)

In [228]:
confusion_mtrx = confusion_matrix(y_test, y_pred)

In [229]:
confusion_mtrx

array([[ 0,  0,  0,  2,  1,  0],
       [ 0,  0,  0,  2,  1,  0],
       [ 0,  0,  0,  5,  6,  1],
       [ 1,  0,  0, 27, 35,  6],
       [ 0,  2,  1, 13, 59, 11],
       [ 0,  0,  0, 12, 20,  8]], dtype=int64)

In [230]:
accuracy = accuracy_score(y_test, y_pred)

In [231]:
accuracy

0.4413145539906103

# Valence

In [223]:
X = Features.iloc[:, :-5].values
y = Features.iloc[:, -5].values

In [224]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [225]:
standard_scaler = StandardScaler()
X_train = standard_scaler.fit_transform(X_train)
X_test = standard_scaler.transform(X_test)

In [226]:
classifier = LogisticRegression(random_state = 0, solver='lbfgs', max_iter=10000)
classifier.fit(X_train, y_train)

C:\Users\Danny\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=10000, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [227]:
y_pred = classifier.predict(X_test)

In [228]:
confusion_mtrx = confusion_matrix(y_test, y_pred)

In [229]:
confusion_mtrx

array([[ 0,  0,  0,  2,  1,  0],
       [ 0,  0,  0,  2,  1,  0],
       [ 0,  0,  0,  5,  6,  1],
       [ 1,  0,  0, 27, 35,  6],
       [ 0,  2,  1, 13, 59, 11],
       [ 0,  0,  0, 12, 20,  8]], dtype=int64)

In [230]:
accuracy = accuracy_score(y_test, y_pred)

In [231]:
accuracy

0.4413145539906103